-- Gestão de Validadores Monday — V2.4
-- Execute uma vez no SQL Editor do mesmo projeto Supabase da Edge Function.

create table if not exists public.gv_acessos (
  id bigint generated by default as identity primary key,
  usuario_id text,
  usuario_email text not null,
  usuario_nome text,
  evento text not null default 'acesso',
  quadro_id text,
  quadro_nome text,
  pagina text,
  build_id text,
  user_agent text,
  criado_em timestamptz not null default now()
);

create table if not exists public.gv_alteracoes (
  id bigint generated by default as identity primary key,
  usuario_id text,
  usuario_email text not null,
  usuario_nome text,
  acao text not null,
  quadro_id text not null,
  quadro_nome text,
  grupo_id text,
  grupo_nome text,
  item_id text,
  item_nome text,
  coluna_id text,
  coluna_nome text,
  valor_anterior jsonb,
  valor_novo jsonb,
  status text not null default 'sucesso',
  erro text,
  criado_em timestamptz not null default now()
);

create index if not exists gv_acessos_criado_em_idx
  on public.gv_acessos (criado_em desc);
create index if not exists gv_acessos_usuario_email_idx
  on public.gv_acessos (usuario_email, criado_em desc);
create index if not exists gv_alteracoes_criado_em_idx
  on public.gv_alteracoes (criado_em desc);
create index if not exists gv_alteracoes_usuario_email_idx
  on public.gv_alteracoes (usuario_email, criado_em desc);
create index if not exists gv_alteracoes_quadro_idx
  on public.gv_alteracoes (quadro_id, criado_em desc);
create index if not exists gv_alteracoes_item_idx
  on public.gv_alteracoes (item_id, criado_em desc);

alter table public.gv_acessos enable row level security;
alter table public.gv_alteracoes enable row level security;

revoke all on table public.gv_acessos from anon, authenticated;
revoke all on table public.gv_alteracoes from anon, authenticated;

grant all on table public.gv_acessos to service_role;
grant all on table public.gv_alteracoes to service_role;
grant usage, select on sequence public.gv_acessos_id_seq to service_role;
grant usage, select on sequence public.gv_alteracoes_id_seq to service_role;

comment on table public.gv_acessos is
  'Auditoria de acessos ao Portal Gestão de Validadores Monday.';
comment on table public.gv_alteracoes is
  'Auditoria das criações e alterações enviadas ao Monday por usuário autenticado.';
